### ISSUE TITLE
Error on render call in controller

### ISSUE THREAD

**Issue by mfpiccolo** [DockYard/postgres_ext-serializers#32]
This project seems pretty awesome.  I was looking forward to trying it out but I can't seem to get anywhere before running into "NoMethodError (undefined method `active_model_serializer' )"

This error occurs on render in the controller action.  Anyone have an idea of what is causing this?

Gems:
rails (4.2.1)
active_model_serializers (0.9.3)
postgres_ext-serializers (0.0.2)

Code:

```
class Api::ProspectsController < Api::BaseController

  def index
    prospects = current_access.prospects
      .search(search_params)
      .includes(:contact, :user_prospects)
      .page(params[:page]).per(params[:per_page])

    render(
      json: prospects,
      meta: {
        total_pages: prospects.total_pages,
        total_count: prospects.total_count
      },
      root: "contacts"
    )
  end
  ...
end
```

Stacktrace:
NoMethodError (undefined method `active_model_serializer' for #<Class:0x007fb36a62cb98>):
  app/controllers/api/prospects_controller.rb:9:in `index'

  Rendered /Users/mfpiccolo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.3ms)
  Rendered /Users/mfpiccolo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.4ms)
  Rendered /Users/mfpiccolo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (8.1ms)
  Rendered /Users/mfpiccolo/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (43.5ms)

**Comment by felixbuenemann** [comment]
Could you inspect `prospects` and check is it's class is `ActiveRecord::Relation`?

**Comment by felixbuenemann** [comment]
I think the issue is, that you're using AMS 0.9.3, but currently the gem only works with 0.8.x. You're using the 0.0.2 version of the gem, which was lacking the proper version constraint.

Please open a new issue, if you still have problem with AMS 0.8 and the master branch of this gem.
